//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.Models
{
    using DoctorMedicalWeb.App_Data;
    using DoctorMedicalWeb.Libreria;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;





    public partial class Usar_UsuarioPersonal
    {
    public bool EstaDesabilitado { get; set; }

        public int? UsuaSecuencia { get; set; }

        [Display(Name = "Correo")]
        [Required(ErrorMessage = "Favor ingresar email.")]
        [RegularExpression(@"[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}", ErrorMessage = "Favor ingresar un correo valido.")]
        public string UsuaEmail { get; set; }

        [NotMapped]
        [Display(Name = "Ingresar email nuevamente")]
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Favor confirmar correo.")]
        [RegularExpression(@"[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}", ErrorMessage = "Favor ingresar un correo valido.")]
        [Compare("UsuaEmail", ErrorMessage = "Los correo deben ser iguales.")]
        public string UsuaEmailConfirmacion { get; set; }

        [Display(Name = "Ingresar clave")]
        [Required(ErrorMessage = "Favor ingresar clave")]
        public string UsuaClave { get; set; }

        [NotMapped]
        [Display(Name = "Ingresar nuevamente clave")]
        [Required(ErrorMessage = "Clave es requerida")]
        [Compare("UsuaClave", ErrorMessage = "Clave no es igual")]
        public string UsuaClaveConfirmacion { get; set; }

        [Display(Name = "Nombre")]
        [Required(ErrorMessage = "Favor introduzca nombre")]
        public string UsuaNombre { get; set; }

        [Display(Name = "Apellido")]
        [Required(ErrorMessage = "Favor introduzca apellido")]
        public string UsuaApellido { get; set; }

        [Display(Name = "Perfil")]
        [Required(ErrorMessage = "Seleccione el perfil")]
        public Nullable<int> RoleSecuencia_fk { get; set; }

        [Display(Name = "Consultorio")]
        [Required(ErrorMessage = "Es requerido Consultorio")]
        [CannotBeEmptyAttribute]//esto es para validar lista
        public List<int> ConsSecuencia { get; set; }

        [Display(Name = "Personal")]
        [Required(ErrorMessage = "Seleccione el Personal")]
        public int PersSecuencia { get; set; }

        
    
        public int DoctSecuencia_fk { get; set; }

        public string DocumentoPasaportCedula { get; set; }
    }
}
