//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.Models
{
    using DoctorMedicalWeb.App_Data;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class Usar_HorarioTrabajo
    {
        public int? DoctSecuencia_fk { get; set; }
        public int? PaisSecuencia_fk { get; set; }
        public int? ClinSecuencia_fk { get; set; }
        public int? ConsSecuencia_fk { get; set; }
        public int HTrabSecuencia { get; set; }
        public int DSemaSecuencia_Fk { get; set; }
        [Display(Name="Repertir Siempre")]
        public bool HTrabRepetirSiempre { get; set; }

         [Display(Name = "Domingo")]
        public bool HTrabSundayDiaHabilitado { get; set; }
        [Display(Name = "Lunes")]
        public bool HTrabMondayDiaHabilitado { get; set; }
        [Display(Name = "Martes")]
        public bool HTrabTuesdayDiaHabilitado { get; set; }
        [Display(Name = "Miercoles")]
        public bool HTrabWednesdayDiaHabilitado { get; set; }
        [Display(Name = "Jueves")]
        public bool HTrabThursdayDiaHabilitado { get; set; }
        [Display(Name = "Viernes")]
        public bool HTrabFridayiaHabilitado { get; set; }
         [Display(Name = "Sábado")]
        public bool HTrabSaturdayDiaHabilitado { get; set; }


      
       
         public bool HTrabDiaHabilitado { get; set; }
   


   
       




        public System.DateTime HTrabFechaCreacion { get; set; }
        public int UsuaSecuenciaCreacion { get; set; }
        public Nullable<System.DateTime> HTrabFechaModificacion { get; set; }
        public Nullable<int> UsuaSecuenciaModificacion { get; set; }
        public bool HTrabEstaDesabilitado { get; set; }
        [Display(Name="División de Hora")]
        public Nullable<int> HTrabPartesHoraSchedule { get; set; }
    
    }
}
