//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.Models
{
    using DoctorMedicalWeb.App_Data;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Usar_TipoFormulario
    {
    public bool EstaDesabilitado { get; set; }
        
        public int? TFormSecuencia { get; set; }
        [DisplayName("Descripcion")]
        [Required(ErrorMessage = "Favor introducir formulario nombre")]
        public string TFormDescripcion { get; set; }


    }
}
