//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.Models
{
    using DoctorMedicalWeb.App_Data;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Usar_Role 
    {
        
           public bool EstaDesabilitado { get; set; }
    
        public int? DoctSecuencia_fk { get; set; }

        public int? RoleSecuencia { get; set; }
        [DisplayName("Role")]
        [Required(ErrorMessage = "Favor introducir role nombre")]
        public string RoleDescripcion { get; set; }
        public Nullable<int> UsuaSecuencia { get; set; }
        public Nullable<System.DateTime> RoleFechaCreacion { get; set; }
        public Nullable<int> UsuaSecuenciaModificacion { get; set; }
        public Nullable<System.DateTime> RoleFechaModificacion { get; set; }

        public virtual Doctor Doctor { get; set; }
    
      
    }
}
