//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.Models
{
    using DoctorMedicalWeb.App_Data;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usar_Consultorio
    {
          [Display(Name = "Desabilitar")]
    public bool EstaDesabilitado { get; set; }
        public int? DoctSecuencia_fk { get; set; }
        public int? ConsSecuencia { get; set; }
        public int? PaisSecuencia_fk { get; set; }
        [Display(Name = "Clínica")]
        [Required(ErrorMessage = "Favor elegir clínica")]
        public int ClinSecuencia_fk { get; set; }   
        [Display(Name = "Código Consultorio")]
        [Required(ErrorMessage = "Favor introduzca código consultorio")]
        public string ConsCodigo { get; set; }
        [Display(Name = "Descripción")]
        public string ConsDescripcion { get; set; }
        [Display(Name = "Dirección")]
        public string ConsDireccion { get; set; }
        [Display(Name = "Teléfono")]
        public string ConsTelefono { get; set; }
        [Display(Name = "Extensión")]
        public string ConsExtencion { get; set; }
        [Display(Name = "Segundo Teléfono")]
        public string ConsTelefono2 { get; set; }
        [Display(Name = "Extensión")]
        public string ConsExtension2 { get; set; }
        public Nullable<int> UsuaSecuenciaCreacion { get; set; }        
        public Nullable<System.DateTime> ConsFechaCreacion { get; set; }
        public Nullable<int> UsuaSecuenciaModificacion { get; set; }
        public Nullable<System.DateTime> ConsFechaModificacion { get; set; }


    }
}
