//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.Models
{
    using DoctorMedicalWeb.App_Data;
    using System;
    using System.Collections.Generic;

    public partial class Usar_PlanFacturaDetalle 

    {
        public int PFDetaSecuencia { get; set; }
        public int UsuSecuencia { get; set; }
        public int PFactSecuencia { get; set; }
        public int PlanSecuencia_fk { get; set; }
    
 
    }
}
