//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.Models
{
    using DoctorMedicalWeb.App_Data;
    using DoctorMedicalWeb.Libreria;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public  class Usar_ConsultaMedicaHistorialEvaluacionFisica 
    {
        public int? DoctSecuencia_fk { get; set; }
        public int? PaisSecuencia_fk { get; set; }
        public int? ClinSecuencia_fk { get; set; }
        public int? ConsSecuencia_fk { get; set; }
        public int? PaciSecuencia_fk { get; set; }
        public int? CMHistSecuencia_fk { get; set; }
      
        [Display(Name="Nota Evaluacion Física")]
        [DataType(DataType.MultilineText)]
        public string EFisiComentario { get; set; }
        [Display(Name = "Evaluacion Física")]
        //[Required(ErrorMessage="prueba")]
        //[CannotBeEmptyAttribute]//esto es para validar lista
        public List<int> EFisiSecuencia_fk { get; set; }
        public bool EstaDesabilitado { get; set; }
   
    }
    
}
