//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.Models
{
    using DoctorMedicalWeb.App_Data;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public  class Usar_ConsultaMedicaHistorialDiagnostico 
    {
        public int? DoctSecuencia_fk { get; set; }
        public int? PaisSecuencia_fk { get; set; }
        public int? ClinSecuencia_fk { get; set; }
        public int? ConsSecuencia_fk { get; set; }
        public int? PaciSecuencia_fk { get; set; }
        public int? CMHistSecuencia { get; set; }
         [Display(Name = "Diagnostico")] 
        public List<int> DiagSecuencia { get; set; }
         [Display(Name = "Nota Diagnostico")] 
        [DataType(DataType.MultilineText)]
        public string DiagComentario { get; set; }
        public bool EstaDesabilitado { get; set; }
    
      
        
    }
}
