//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.Models
{
    using DoctorMedicalWeb.App_Data;
    using System;
    using System.Collections.Generic;
    
    public partial class Usar_Auditoria
    {
    public bool EstaDesabilitado { get; set; }
        public int AudiSecuencia { get; set; }
        public int PaisSecuencia { get; set; }
        public int ClinSecuencia { get; set; }
        public int ConsSecuencia { get; set; }
        public int DoctSecuencia { get; set; }
        public Nullable<int> PersSecuencia { get; set; }
        public Nullable<int> TPersSecuencia { get; set; }
        public System.DateTime AudiFechaMaquina { get; set; }
        public System.DateTime AudiFechaServidor { get; set; }
        public string AudiValorOriginal { get; set; }
        public string AudiValorNuevo { get; set; }
        public int UsuaCodigo { get; set; }
        public string AudiIpMaquina { get; set; }
        public int PagiSecuencia { get; set; }
        public int TablSecuencia { get; set; }
        public int Accisecuencia { get; set; }
    }
}
