//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.Models
{
    using DoctorMedicalWeb.App_Data;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usar_Receta
    {


        public int? DoctSecuencia_fk { get; set; }
        public int? PaisSecuencia_fk { get; set; }
        public int? ClinSecuencia_fk { get; set; }
        public int? ConsSecuencia_fk { get; set; }
        public int? PaciSecuencia_fk { get; set; }
        public int? ReceSecuencia { get; set; }
        public Nullable<int> CMHistSecuencia_fk { get; set; }

        [Display(Name = "Fecha")]
        public Nullable<System.DateTime> ReceFecha { get; set; }
        public string ReceFechaString { get; set; }

        [Display(Name = "Nombre")]
        public string RecNombre { get; set; }

        public string RecSinConsultaNombre { get; set; }

        public string ReceInstruccionesFarmacia { get; set; }
        public string ReceInstruccionesAlPaciente { get; set; }
        [Display(Name = "Receta")]
        [DataType(DataType.MultilineText)]
        [Required(ErrorMessage = "Favor escribir la receta.")]
        public string ReceComentario { get; set; }

        public Nullable<int> UsuaSecuenciaCreacion { get; set; }
        public Nullable<System.DateTime> UsuaFechaCreacion { get; set; }
        public Nullable<int> UsuaSecuenciaModificacion { get; set; }
        public Nullable<System.DateTime> UsuaFechaModificacion { get; set; }
        public bool EstaDesabilitado { get; set; }






    }
}
