//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.Models
{
    using DoctorMedicalWeb.App_Data;
    using DoctorMedicalWeb.Libreria;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public  class Usar_ConsultaMedicaHistorialMotivoConsulta 
    {
        public int? DoctSecuencia_fk { get; set; }
        public int? PaisSecuencia_fk { get; set; }
        public int? ClinSecuencia_fk { get; set; }
        public int? ConsSecuencia_fk { get; set; }
        public int? PaciSecuencia_fk { get; set; }
        public int? CMHistSecuencia_fk { get; set; }
        [Display(Name = "Nota Motivo Consulta")]
        [DataType(DataType.MultilineText)]
        public string MotiComentario { get; set; }
        
        [Display(Name = "Motivo de Consulta")]
        [Required(ErrorMessage = "Es requerido motivo de consulta")]
        [CannotBeEmptyAttribute]//esto es para validar lista
        public List<int> MConsSecuencia_fk { get; set; }

        public bool EstaDesabilitado { get; set; }
    }
}
