//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.Models
{
    using DoctorMedicalWeb.App_Data;
    using System;
    using System.Collections.Generic;

    public partial class Usar_Formulario 
    {
           public bool EstaDesabilitado { get; set; }
        public int FormSecuencia { get; set; }
        public string FormDescripcion { get; set; }
        public int TFormSecuencia_fk { get; set; }
    
      
    }
}
