//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.Models
{
    using DoctorMedicalWeb.App_Data;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class Usar_Paciente
    {



        public int? DoctSecuencia_fk { get; set; }
        public int? PaisSecuencia_fk { get; set; }
        public int? ClinSecuencia_fk { get; set; }
        public int? ConsSecuencia_fk { get; set; }
        public int? PaciSecuencia { get; set; }

        [Display(Name="Codigo")]
        public string PaciCodigo { get; set; }
        [Display(Name = "Tp. Sanguineo")]
        public Nullable<int> GSangSecuencia_fk { get; set; }

        [Required(ErrorMessage = "Introduzca documento")]
        public string PaciDocumento { get; set; }
        [Display(Name = "Cédula o Pasaporte")]
        [Required(ErrorMessage = "Seleccione tipo documento")]
        public int TDSecuencia { get; set; }
        [Display(Name = "Número Seguro Social")]
        public string PaciNumeroSeguroSocial { get; set; }
        [Display(Name = "Seguro")]
        public Nullable<int> IAsegSecuencia { get; set; }
        [Display(Name = "Plan")]
        public Nullable<int> IAPlanSecuencia { get; set; }
        [Display(Name = "Poliza")]
        public string  PaciNumeroPoliza { get; set; }
        [Display(Name = "Es Menor")]
        public bool EsMenor { get; set; }
        [Display(Name = "Nombre")]
        [Required(ErrorMessage = "Favor ingresar nombre")]
        public string PaciNombre { get; set; }
        [Display(Name = "Primer Apellido")]
        [Required(ErrorMessage = "Favor ingresar primer apellido")]
        public string PaciApellido1 { get; set; }
        [Display(Name = "Segundo Apellido")]
        public string PaciApellido2 { get; set; }

        public string PaciApodo { get; set; }
        public string NombreCompleto
        {

            get
            {
                string compl = this.PaciNombre + " " + this.PaciApellido1 + " " + this.PaciApellido2;
                return compl;
            }

        }
        [Display(Name = "Fec. Nacimiento")]
        [Required(ErrorMessage = "Favor ingresar fecha nacimiento")]
        public Nullable<System.DateTime> PaciFechaNacimiento { get; set; }
        public string PaciFechaNacimientoString
        {
            get
            {
                string fecha = "";
                if (PaciFechaNacimiento != null)
                {
                    fecha = this.PaciFechaNacimiento.Value.ToString("dd/MM/yyyy");

                }
                return fecha;
            }
            set
            {
                string fecha = "";
                if (PaciFechaNacimiento != null)
                {
                    fecha = this.PaciFechaNacimiento.Value.ToString("dd/MM/yyyy");

                }
                value = fecha;
            }
        }
        [Display(Name = "Lugar Nacimiento")]
        public string PaciLugarNacimiento { get; set; }
        [Display(Name = "Edad")]
        public int? PaciEdad { get; set; }
        [Display(Name = "Correo Electrónico")]
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}", ErrorMessage = "Favor ingresar un correo valido.")]
        public string PaciEmail { get; set; }
        [Display(Name = "Facebook")]
        public string PaciFacebook { get; set; }
        [Display(Name = "Dirección")]
        public string PaciDireccion { get; set; }
        [Display(Name = "Teléfono")]
        public string PaciTelefono { get; set; }
        [Display(Name = "Celular")]
        public string PaciCelular { get; set; }
        public Nullable<int> PaciCodigoPostal { get; set; }
        [Display(Name = "Estado Civil")]
        public string PaciEstadoCivil { get; set; }
        [Display(Name = "Profesión")]
        public string PaciProfesion { get; set; }
        [Display(Name = "Emergencia Nombre")]
        public string PaciNombreEmergencia { get; set; }
        [Display(Name = "Emergencia Apellido")]
        public string PaciApellidoEmergencia { get; set; }
        [Display(Name = "Emergencia Dirección")]
        public string PaciDireccionEmergencia { get; set; }
        [Display(Name = "Emergencia Teléfono")]
        public string PaciTelefonoEmergencia { get; set; }
        public Nullable<int> UsuaSecuenciaCreacion { get; set; }
        [Display(Name = "Fecha Creacion")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> UsuaFechaCreacion { get; set; }
        public string UsuaFechaCreacionString
        {
            get
            {
                string fecha = "";
                if (UsuaFechaCreacion != null)
                {
                    fecha = this.UsuaFechaCreacion.Value.ToString("dd/MM/yyyy");

                }
                return fecha;
            }
            set
            {
                string fecha = "";
                if (UsuaFechaCreacion != null)
                {
                    fecha = this.UsuaFechaCreacion.Value.ToString("dd/MM/yyyy");

                }
                value = fecha;
            }
        }
        public Nullable<int> UsuaSecuenciaModificacion { get; set; }
        public Nullable<System.DateTime> UsuaFechaModificacion { get; set; }
        [Display(Name = "Foto")]
        public string PaciFotoPath { get; set; }
        public string PaciFotoNombre { get; set; }
        [Display(Name = "Genero")]
        [Required(ErrorMessage = "Favor seleccionar genero")]
        public string PaciGenero { get; set; }
        
        public bool EstaDesabilitado { get; set; }

        public string clinRazonSocial { get; set; }
        public string ConsCodigo { get; set; }
        public string ConsDescripcion { get; set; }
        //public string FechaNacimientoString { get; set; }





    }
}
