//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.Models
{
    using System;
    using System.Collections.Generic;
    using DoctorMedicalWeb.App_Data;
    
    public  class Usar_Accione
    {
       
    
        public int AcciSecuencia { get; set; }
        public string AcciNombre { get; set; }
        public bool EstaDesabilitado { get; set; }
          }
}
