//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.Models
{
    using DoctorMedicalWeb.App_Data;
    using System;
    using System.Collections.Generic;

    public partial class Usar_Procedimiento 
    {
        
    
        public int DoctSecuencia_fk { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public int ClinSecuencia_fk { get; set; }
        public int ConsSecuencia_fk { get; set; }
        public int ProcSecuencia { get; set; }
        public string ProcCodigo { get; set; }
        public string ProcNombre { get; set; }
        public string ProcDescripcion { get; set; }
        public Nullable<int> MoneSecuencia_fk { get; set; }
        public decimal ProcPrecio { get; set; }
        public Nullable<decimal> ProcItbis { get; set; }
        public Nullable<int> CContSecuencia { get; set; }
        public int UsuaSecuenciaCreacion { get; set; }
        public System.DateTime ProcFechaCreacion { get; set; }
        public int UsuaSecuenciaModificacion { get; set; }
        public System.DateTime ProcFechaModificacion { get; set; }
    
         public bool EstaDesabilitado { get; set; }
    }
}
