//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.Models
{
    using DoctorMedicalWeb.App_Data;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Usar_Doctor
    {
        
           public bool EstaDesabilitado { get; set; }
        public int DoctSecuencia { get; set; }
        public int UsuSecuencia { get; set; }
        [Display(Name = "CUPRE")]
        public string DoctCUPRE { get; set; }
        [Display(Name="Cedula o Pasaporte")]
        [Required(ErrorMessage="Favor ingresar cedula o pasaporte")]
        public string DoctDocumento { get; set; }    
        [Required(ErrorMessage = "Favor seleccionar  documento.")]
        public Nullable<int> TDSecuencia { get; set; }
        [Display(Name="Nombre")]
        [Required(ErrorMessage="Favor ingresar nombre")]
        public string DoctNombre { get; set; }
        [Display(Name="Apellido")]
        [Required(ErrorMessage="Favor ingresar Apellido")]
        public string DoctApellido { get; set; }

        [Display(Name = "Ingresar clave")]
        [Required(ErrorMessage = "Favor ingresar clave")]
        [DataType(DataType.Password)]
        public string UsuaClave { get; set; }

        [Display(Name = "Correo")]
        [Required(ErrorMessage = "Favor ingresar email.")]
        [RegularExpression(@"[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}", ErrorMessage = "Favor ingresar un correo valido.")]
        public string UsuaEmail { get; set; }

        [NotMapped]
        [Display(Name = "Ingresar nuevamente clave")]
        [Required(ErrorMessage = "Clave es requerida")]
        [Compare("UsuaClave", ErrorMessage = "Clave no es igual")]
        [DataType(DataType.Password)]
        public string UsuaClaveConfirmacion { get; set; }

        [Display(Name = "Especialidad")]
        [Required(ErrorMessage = "Favor seleccionar especialidad.")]
        public int EspeSecuencia { get; set; }
        [Display(Name = "Direccion")]
        [Required(ErrorMessage = "Favor ingrese direccion.")]
        public string DoctDireccion { get; set; }
        [Display(Name = "Telefono")]
        [Required(ErrorMessage = "Favor ingrese telefono.")]
        public string DoctTelefono { get; set; }
        [Display(Name = "Celular")]
        [DataType(DataType.PhoneNumber)]
        [Required(ErrorMessage = "Favor ingrese celular.")]
        public string DoctCelular { get; set; }
        [Display(Name = "Genero")]
      
        [Required(ErrorMessage = "Favor seleccione genero.")]
        public string DoctGenero { get; set; }
       
        

        public Nullable<int> UsuaSecuenciaCreacion { get; set; }
             [Display(Name = "Fecha Creación")]
        public Nullable<System.DateTime> DoctFechaCreacion { get; set; }
             public string DoctFechaCreacionString
             {
                 get
                 {
                     string fecha = "";
                     if (DoctFechaCreacion != null)
                     {
                         fecha = this.DoctFechaCreacion.Value.ToString("dd/MM/yyyy");

                     }
                     return fecha;
                 }
                 set
                 {
                     string fecha = "";
                     if (DoctFechaCreacion != null)
                     {
                         fecha = this.DoctFechaCreacion.Value.ToString("dd/MM/yyyy");

                     }
                     value = fecha;
                 }
             }
        public Nullable<int> UsuaSecuenciaModificacion { get; set; }
        public Nullable<System.DateTime> DoctFechaModificacion { get; set; }


        public int PaisSecuencia { get; set; }

        public string DoctFotoPath { get; set; }
        public string DoctFotoNombre { get; set; }

        [DisplayName("Fecha de Nacimiento")/*, Required(ErrorMessage = "Debe ingresar su fecha de nacimiento.")*/]
        //[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> DoctFechaNacimiento { get; set; }

        
    }
}
