//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.Models
{
    using DoctorMedicalWeb.App_Data;
    using DoctorMedicalWeb.Libreria;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

   

    //public class EnsureOneElementAttribute : ValidationAttribute
    //{
    //    public override bool IsValid(object value)
    //    {
    //        var list = value as IList;
    //        //var list = value;
    //        if (list != null)
    //        {
    //            return list.Count > 0;
    //        }
    //        return false;
    //    }
    //}

    public class DropDownValue
    {
        public string Text { get; set; }
        public string Value { get; set; }

    }

    public partial class Usar_Personal
    {
       

        public int? DoctSecuencia_fk { get; set; }
        public int? PersSecuencia { get; set; }
        public int? PaisSecuencia_fk { get; set; }
  

        [Required(ErrorMessage = "Favor ingresar cedula o pasaporte")]
        public string PersDocumento { get; set; }

        //[Required(ErrorMessage = "Favor ingresar consultorio")]
        //[EnsureOneElement(ErrorMessage = "Favor ingresar consultorio")]
        //[Required(ErrorMessage = "This Field Is Required")]
        //public List<int> ConsSecuencia { get; set; }

        //[Required(ErrorMessage=  "This Field Is Required")]
        //[CannotBeEmptyAttribute] 
        //[Display(Name = "Consultorio")]
        //public List<int> ConsSecuencia { get; set; }
        //        public List<vw_UsuarioConsultorios> ConsSecuenciaPru { get; set; }
        //[Required(ErrorMessage = "DropDownList value is Required")]
        //public List<DropDownValue> ConsSecuenciaPru { get; set; }
        //[CannotBeEmptyAttribute]
        //public List<int> ConsSecuencia { get; set; }
        //public List<vw_UsuarioConsultorios> ConsSecuenciap { get; set; }
        public int TDSecuencia_fk { get; set; }
        [Display(Name = "Nombre")]
        [Required(ErrorMessage = "Favor ingresar nombre")]
        public string PersNombre { get; set; }
        [Display(Name = "Apellido")]
        [Required(ErrorMessage = "Favor ingresar apellido")]
        public string PersApellido { get; set; }
        [Display(Name = "Fecha Nacimiento")]
        [Required(ErrorMessage = "Favor ingresar fecha nacimiento")]
        public Nullable<System.DateTime> PersFechaNacimiento { get; set; }
        [Display(Name = "Dirección")]
        public string PersDireccion { get; set; }
        [Display(Name = "Categoria Personal")]
        [Required(ErrorMessage = "Favor ingresar categoria personal")]
        public int CPersSecuencia_FK { get; set; }
        [Display(Name = "Telefono")]
        [Required(ErrorMessage = "Favor ingresar teléfono")]
        public string PersTelefono { get; set; }
        [Display(Name = "Celular")]
        [Required(ErrorMessage = "Favor ingresar celular")]
        public string PersCelular { get; set; }
        public bool?  EstaActivo { get; set; }
        [Display(Name = "Genero")]
        [Required(ErrorMessage = "Favor ingresar genero")]
        public string PersGenero { get; set; }
        public Nullable<int> UsuaCreacion { get; set; }
        public Nullable<System.DateTime> PersFechaCreacion { get; set; }
        public string PersFechaCreacionString
        {
            get
            {
                string fecha = "";
                if (PersFechaCreacion != null)
                {
                    fecha = this.PersFechaCreacion.Value.ToString("dd/MM/yyyy");

                }
                return fecha;
            }
            set
            {
                string fecha = "";
                if (PersFechaCreacion != null)
                {
                    fecha = this.PersFechaCreacion.Value.ToString("dd/MM/yyyy");

                }
                value = fecha;
            }
        }
        public Nullable<int> UsuaModificacion { get; set; }
        public Nullable<System.DateTime> PersFechaModificacion { get; set; }

           public bool EstaDesabilitado { get; set; }
    }
}
