//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.Models
{
    using DoctorMedicalWeb.App_Data;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usar_Clinica
    {

    public bool EstaDesabilitado { get; set; }
        public int? clinSecuencia { get; set; }
        public int? PaisSecuencia_fk { get; set; }
        [Display(Name = "Razón Social")]
        [Required(ErrorMessage = "Favor introduzca razón social")]
        public string clinRazonSocial { get; set; }

        public string clinEstablecimiento { get; set; }
        public string clinOrganismoSuperior { get; set; }
        [Display(Name = "Dirección")]
        public string clinDireccion { get; set; }
        [Display(Name = "Teléfono")]
        public string clinTelefono { get; set; }
        [Display(Name = "Segundo Teléfono")]
        public string clinTelefono2 { get; set; }
        [Display(Name = "RNC")]
        public Nullable<int> clinRNC { get; set; }
        public Nullable<int> clinFax { get; set; }
        [Url]
        [Display(Name = "Página Web")]
        public string clinPaginaWeb { get; set; }
        [Display(Name = "Correo Electrónico")]
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}", ErrorMessage = "Favor ingresar un correo valido.")]
        public string clinEmail { get; set; }
        public string clinFotoName { get; set; }
        [Display(Name = "Foto")]
        public string clinFotoPath { get; set; }
        public string clinCuerpoCartaCabecera { get; set; }
        public string clinCuerpoCartaPie { get; set; }
        public Nullable<decimal> clinLatitud { get; set; }
        public Nullable<decimal> clinLongitud { get; set; }
   
        public Nullable<int> usuaSecuenciaCreacion { get; set; }
        public Nullable<int> usuaSecuenciaModificacion { get; set; }
        [Display(Name = "Fecha Creacion")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> clinFechaCreacion { get; set; }
        public Nullable<System.DateTime> clinFechaModificacion { get; set; }


    }
}
