//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.Models
{

    using System;
    using System.ComponentModel.DataAnnotations;


    public  class Usar_Enfermedad
    {

        public int? DoctSecuencia_fk { get; set; }
        public int? PaisSecuencia_fk { get; set; }
        public int? ClinSecuencia_fk { get; set; }
        public int? ConsSecuencia_fk { get; set; }
        public int? EnfeSecuencia { get; set; }
        [Display(Name="Nombre")]
        [Required(ErrorMessage = "Favor introducir nombre")]
        public string EnfeNombre { get; set; }
                [Display(Name = "Descripción")]
        public string EnfeDescripcion { get; set; }

    }
}
