//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.Models
{
    using DoctorMedicalWeb.App_Data;
    using System;
    using System.Collections.Generic;

    public partial class Usar_TipoCompromiso 
    {
        public int TCompSecuencia { get; set; }
        public string TCompCodigo { get; set; }
        public string TCompNombre { get; set; }
        public string TCompDescripcion { get; set; }    public bool EstaDesabilitado { get; set; }
    }
}
