//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalisisClinico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnalisisClinico()
        {
            this.RecetaAnalisisClinicoes = new HashSet<RecetaAnalisisClinico>();
        }
    
        public int DoctSecuencia_fk { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public int ClinSecuencia_fk { get; set; }
        public int ConsSecuencia_fk { get; set; }
        public int AClinSecuencia { get; set; }
        public string AClinCodigo { get; set; }
        public string AClinNombre { get; set; }
        public string AClinDescripcion { get; set; }
        public string AClinTipoDeMuestra { get; set; }
        public string AClinTiempoDeProceso { get; set; }
        public string AClinCondicionesDelPaciente { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecetaAnalisisClinico> RecetaAnalisisClinicoes { get; set; }
    }
}
