//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivosPaciente
    {
        public int DoctSecuencia_fk { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public int ClinSecuencia_fk { get; set; }
        public int ConsSecuencia_fk { get; set; }
        public int PaciSecuencia_fk { get; set; }
        public int CMHistSecuencia_fk { get; set; }
        public int APaciSecuencia { get; set; }
        public int TAPaciSecuencia_fk { get; set; }
        public System.DateTime APaciFecha { get; set; }
        public string APaciCodigo { get; set; }
        public byte[] APaciImagen { get; set; }
        public string APaciDescripcion { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual TipoArchivoPaciente TipoArchivoPaciente { get; set; }
    }
}
