//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaMedicaEmbarazo
    {
        public int DoctSecuencia_fk { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public int ClinSecuencia_fk { get; set; }
        public int ConsSecuencia_fk { get; set; }
        public int PaciSecuencia_fk { get; set; }
        public int CMHistSecuencia_fk { get; set; }
        public bool CMEmbEmbarazada { get; set; }
        public System.DateTime CMEmbEmbarazadaFecha { get; set; }
        public Nullable<int> CMEmbEmbarazadaSemanas { get; set; }
        public Nullable<int> CMEmbEmbarazadaDias { get; set; }
        public Nullable<int> CMEmbEmbarazadaMeses { get; set; }
        public System.DateTime CMEmbEmbarazadaFechaProbableParto { get; set; }
    }
}
