//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaMedicaEnfermeda
    {
        public int DoctSecuencia_fk { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public int ClinSecuencia_fk { get; set; }
        public int ConsSecuencia_fk { get; set; }
        public int PaciSecuencia_fk { get; set; }
        public int CMediSecuencia_fk { get; set; }
        public int EnfeSecuencia_fk { get; set; }
        public string EnfeComentario { get; set; }
        public bool EnfermedadActiva { get; set; }
        public Nullable<System.DateTime> FechaDeDiagnostico { get; set; }
        public bool EnfermedadInfecciosa { get; set; }
        public Nullable<int> EdadMomentoDiagnosticado { get; set; }
    
        public virtual ConsultaMedica ConsultaMedica { get; set; }
        public virtual Enfermedad Enfermedad { get; set; }
    }
}
