//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaMedicaCirugia
    {
        public int DoctSecuencia_fk { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public int ClinSecuencia_fk { get; set; }
        public int ConsSecuencia_fk { get; set; }
        public int PaciSecuencia_fk { get; set; }
        public int CMediSecuencia_fk { get; set; }
        public int CiruSecuencia_fk { get; set; }
        public string CiruComentario { get; set; }
        public Nullable<int> EdadCirugia { get; set; }
    
        public virtual Cirugia Cirugia { get; set; }
        public virtual ConsultaMedica ConsultaMedica { get; set; }
    }
}
