//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaMedicaHistorial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConsultaMedicaHistorial()
        {
            this.ConsultaMedicaHistorialEvaluacionFisicas = new HashSet<ConsultaMedicaHistorialEvaluacionFisica>();
            this.ConsultaMedicaHistorialTratamientoes = new HashSet<ConsultaMedicaHistorialTratamiento>();
            this.ConsultaMedicaHistorialDiagnosticoes = new HashSet<ConsultaMedicaHistorialDiagnostico>();
            this.ConsultaMedicaHistorialMotivoConsultas = new HashSet<ConsultaMedicaHistorialMotivoConsulta>();
        }
    
        public int DoctSecuencia_fk { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public int ClinSecuencia_fk { get; set; }
        public int ConsSecuencia_fk { get; set; }
        public int PaciSecuencia_fk { get; set; }
        public int CMHistSecuencia { get; set; }
        public string TratComentario { get; set; }
        public string MotiComentario { get; set; }
        public string EFisiComentario { get; set; }
        public string DiagComentario { get; set; }
        public Nullable<System.DateTime> CMHistFechaUltimaRegla { get; set; }
        public Nullable<decimal> CMHistIndiceMasaCorporal { get; set; }
        public string CMHistUnidadesMedidaPeso { get; set; }
        public Nullable<decimal> CMHistPeso { get; set; }
        public string CMHistUnidadesMedidaTalla { get; set; }
        public Nullable<decimal> CMHistTalla { get; set; }
        public string CMHistCodigo { get; set; }
        public Nullable<System.DateTime> CMHistFecha { get; set; }
        public Nullable<System.TimeSpan> CMHistHora { get; set; }
        public string CMHistComentario { get; set; }
        public Nullable<int> UsuaSecuenciaCreacion { get; set; }
        public System.DateTime UsuaFechaCreacion { get; set; }
        public Nullable<int> UsuaSecuenciaModificacion { get; set; }
        public Nullable<System.DateTime> UsuaFechaModificacion { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Paciente Paciente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultaMedicaHistorialEvaluacionFisica> ConsultaMedicaHistorialEvaluacionFisicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultaMedicaHistorialTratamiento> ConsultaMedicaHistorialTratamientoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultaMedicaHistorialDiagnostico> ConsultaMedicaHistorialDiagnosticoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultaMedicaHistorialMotivoConsulta> ConsultaMedicaHistorialMotivoConsultas { get; set; }
    }
}
