//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorTimeZone
    {
        public int DoctTimeZoneSecuencia { get; set; }
        public int UsuarioId { get; set; }
        public int ClinSecuencia { get; set; }
        public int ConsSecuencia { get; set; }
        public int DoctId { get; set; }
        public int CountryCityId { get; set; }
        public string CountryCity { get; set; }
    }
}
