//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.ArchivosPacientes = new HashSet<ArchivosPaciente>();
            this.Citas = new HashSet<Cita>();
            this.ConsultaMedicas = new HashSet<ConsultaMedica>();
            this.ConsultaMedicaHistorials = new HashSet<ConsultaMedicaHistorial>();
            this.Consultorios = new HashSet<Consultorio>();
            this.HorarioTrabajoes = new HashSet<HorarioTrabajo>();
            this.ImagenDoctors = new HashSet<ImagenDoctor>();
            this.InstitucionesAseguradoras = new HashSet<InstitucionesAseguradora>();
            this.Pacientes = new HashSet<Paciente>();
            this.Procedimientos = new HashSet<Procedimiento>();
            this.Recetas = new HashSet<Receta>();
            this.TipoArchivoPacientes = new HashSet<TipoArchivoPaciente>();
        }
    
        public int DoctSecuencia { get; set; }
        public int UsuSecuencia { get; set; }
        public string DoctCUPRE { get; set; }
        public string DoctDocumento { get; set; }
        public Nullable<int> TDSecuencia { get; set; }
        public string DoctNombre { get; set; }
        public string DoctApellido { get; set; }
        public Nullable<System.DateTime> DoctFechaNacimiento { get; set; }
        public int EspeSecuencia { get; set; }
        public string DoctDireccion { get; set; }
        public string DoctTelefono { get; set; }
        public string DoctCelular { get; set; }
        public Nullable<int> UsuaSecuenciaCreacion { get; set; }
        public Nullable<System.DateTime> DoctFechaCreacion { get; set; }
        public Nullable<int> UsuaSecuenciaModificacion { get; set; }
        public Nullable<System.DateTime> DoctFechaModificacion { get; set; }
        public string DoctGenero { get; set; }
        public int PaisSecuencia { get; set; }
        public string DoctFotoPath { get; set; }
        public string DoctFotoNombre { get; set; }
        public bool EstaDesabilitado { get; set; }
        public string NombreDoctoRecetaEncab { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArchivosPaciente> ArchivosPacientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cita> Citas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultaMedica> ConsultaMedicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultaMedicaHistorial> ConsultaMedicaHistorials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consultorio> Consultorios { get; set; }
        public virtual Especialidade Especialidade { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorarioTrabajo> HorarioTrabajoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImagenDoctor> ImagenDoctors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstitucionesAseguradora> InstitucionesAseguradoras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paciente> Pacientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Procedimiento> Procedimientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receta> Recetas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoArchivoPaciente> TipoArchivoPacientes { get; set; }
    }
}
