//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EspecialidadFormularioCampos
    {
        public int EspeSecuencia_fk { get; set; }
        public int FormSecuencia_fk { get; set; }
        public int FCampSecuencia_fk { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual Especialidade Especialidade { get; set; }
        public virtual FormularioCampos FormularioCampos { get; set; }
        public virtual Formulario Formulario { get; set; }
    }
}
