//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.FacturaDetalles = new HashSet<FacturaDetalle>();
        }
    
        public int DoctSecuencia_fk { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public int ClinSecuencia_fk { get; set; }
        public int ConsSecuencia_fk { get; set; }
        public int PaciSecuencia_fk { get; set; }
        public Nullable<int> PersSecuencia_fk { get; set; }
        public Nullable<int> CPersSecuencia_fk { get; set; }
        public int FactSecuencia { get; set; }
        public Nullable<int> FactCodigo { get; set; }
        public System.DateTime FactFecha { get; set; }
        public int FEstaSecuencia_fk { get; set; }
        public Nullable<int> CFisCodigo { get; set; }
        public string FactNCF { get; set; }
        public Nullable<int> TPagoSecuencia_fk { get; set; }
        public decimal FactReclamado { get; set; }
        public decimal FactCobertura { get; set; }
        public decimal FactSubtotal { get; set; }
        public decimal FactItbis { get; set; }
        public decimal FactDescuento { get; set; }
        public decimal FactTotal { get; set; }
        public int UsuaSecuencia { get; set; }
        public Nullable<decimal> FactPorDescuento { get; set; }
        public Nullable<decimal> FactPagado { get; set; }
        public int UsuaSecuenciaCreacion { get; set; }
        public System.DateTime FactFechaCreacion { get; set; }
        public int UsuaSecuenciaModificacion { get; set; }
        public System.DateTime FactFechaModificacion { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual FacturaEstado FacturaEstado { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual TipoPago TipoPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaDetalle> FacturaDetalles { get; set; }
    }
}
