//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioTrabajoDestalle
    {
        public int DoctSecuencia_fk { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public int ClinSecuencia_fk { get; set; }
        public int ConsSecuencia_fk { get; set; }
        public int DSemaSecuencia_Fk { get; set; }
        public System.TimeSpan hi { get; set; }
        public System.TimeSpan hf { get; set; }
        public string ht { get; set; }
    
        public virtual HorarioTrabajo HorarioTrabajo { get; set; }
    }
}
