//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorarioTrabajo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HorarioTrabajo()
        {
            this.HorarioTrabajoDestalles = new HashSet<HorarioTrabajoDestalle>();
        }
    
        public int DoctSecuencia_fk { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public int ClinSecuencia_fk { get; set; }
        public int ConsSecuencia_fk { get; set; }
        public int HTrabSecuencia { get; set; }
        public int DSemaSecuencia_Fk { get; set; }
        public bool HTrabRepetirSiempre { get; set; }
        public bool HTrabDiaHabilitado { get; set; }
        public System.DateTime HTrabFechaCreacion { get; set; }
        public int UsuaSecuenciaCreacion { get; set; }
        public Nullable<System.DateTime> HTrabFechaModificacion { get; set; }
        public Nullable<int> UsuaSecuenciaModificacion { get; set; }
        public bool HTrabEstaDesabilitado { get; set; }
        public Nullable<int> HTrabPartesHoraSchedule { get; set; }
    
        public virtual Clinica Clinica { get; set; }
        public virtual Consultorio Consultorio { get; set; }
        public virtual DiasSemana DiasSemana { get; set; }
        public virtual Doctor Doctor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorarioTrabajoDestalle> HorarioTrabajoDestalles { get; set; }
    }
}
