//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstitucionAseguradoraPlane
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstitucionAseguradoraPlane()
        {
            this.Pacientes = new HashSet<Paciente>();
        }
    
        public int DoctSecuencia { get; set; }
        public int ClinSecuencia { get; set; }
        public int ConsSecuencia { get; set; }
        public int IAsegSecuencia { get; set; }
        public int IAPlanSecuencia { get; set; }
        public string IAPlanDescripcion { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual InstitucionesAseguradora InstitucionesAseguradora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paciente> Pacientes { get; set; }
    }
}
