//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametro
    {
        public int ParaSecuencia { get; set; }
        public string ParaNombre { get; set; }
        public string ParaDescripcion { get; set; }
        public bool Seleccionado { get; set; }
    }
}
