//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PediatraParto
    {
        public string Lugar { get; set; }
        public Nullable<bool> cesaria { get; set; }
        public Nullable<bool> posicionCefalica { get; set; }
        public Nullable<bool> posicionPodalica { get; set; }
        public string apgar { get; set; }
        public string partogamma { get; set; }
        public Nullable<bool> anestesiaNO { get; set; }
        public Nullable<bool> anestesiaraquidea { get; set; }
        public Nullable<bool> anestesiaperidural { get; set; }
        public Nullable<bool> anestesiatotal { get; set; }
        public string observaciones { get; set; }
        public Nullable<decimal> pesokg { get; set; }
        public Nullable<decimal> alturacm { get; set; }
        public Nullable<decimal> pccm { get; set; }
        public Nullable<int> ombligoDIas { get; set; }
        public string OMBLIGOOBSERVACIONES { get; set; }
        public bool EstaDesabilitado { get; set; }
    }
}
