//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIATRIAeMBARAZO
    {
        public Nullable<int> GESTACIONNumero { get; set; }
        public string obstetra { get; set; }
        public Nullable<int> duracionSemanas { get; set; }
        public Nullable<bool> diabetes { get; set; }
        public Nullable<bool> hipertension { get; set; }
        public Nullable<bool> tramatismo { get; set; }
        public string infrecciones { get; set; }
        public string asma { get; set; }
        public string mediacion { get; set; }
        public string observacion { get; set; }
        public bool EstaDesabilitado { get; set; }
    }
}
