//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personal()
        {
            this.Facturas = new HashSet<Factura>();
        }
    
        public int DoctSecuencia_fk { get; set; }
        public int PersSecuencia { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public string PersDocumento { get; set; }
        public int TDSecuencia_fk { get; set; }
        public Nullable<int> UsuaSecuencia { get; set; }
        public string PersNombre { get; set; }
        public string PersApellido { get; set; }
        public Nullable<System.DateTime> PersFechaNacimiento { get; set; }
        public string PersDireccion { get; set; }
        public int CPersSecuencia_FK { get; set; }
        public string PersTelefono { get; set; }
        public string PersCelular { get; set; }
        public bool EstaActivo { get; set; }
        public string PersGenero { get; set; }
        public Nullable<int> UsuaCreacion { get; set; }
        public Nullable<System.DateTime> PersFechaCreacion { get; set; }
        public Nullable<int> UsuaModificacion { get; set; }
        public Nullable<System.DateTime> PersFechaModificacion { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Facturas { get; set; }
        public virtual Pai Pai { get; set; }
    }
}
