//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanFacturaDetalle
    {
        public int PFDetaSecuencia { get; set; }
        public int UsuSecuencia { get; set; }
        public int PFactSecuencia { get; set; }
        public int PlanSecuencia_fk { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual Plane Plane { get; set; }
        public virtual PlanFactura PlanFactura { get; set; }
    }
}
