//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanFactura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanFactura()
        {
            this.PlanFacturaDetalles = new HashSet<PlanFacturaDetalle>();
        }
    
        public int UsuSecuencia { get; set; }
        public int PFactSecuencia { get; set; }
        public Nullable<int> PFactCodigo { get; set; }
        public System.DateTime PFactFecha { get; set; }
        public int PFEstaSecuencia_fk { get; set; }
        public Nullable<int> CFisCodigo { get; set; }
        public string PFactNCF { get; set; }
        public Nullable<int> TPagoSecuencia_fk { get; set; }
        public decimal PFactReclamado { get; set; }
        public decimal PFactCobertura { get; set; }
        public decimal PFactSubtotal { get; set; }
        public decimal PFactItbis { get; set; }
        public decimal PFactDescuento { get; set; }
        public decimal PFactTotal { get; set; }
        public int UsuaSecuencia { get; set; }
        public Nullable<decimal> PFactPorDescuento { get; set; }
        public Nullable<decimal> PFactPagado { get; set; }
        public int UsuaSecuenciaCreacion { get; set; }
        public System.DateTime PFactFechaCreacion { get; set; }
        public int UsuaSecuenciaModificacion { get; set; }
        public System.DateTime PFactFechaModificacion { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanFacturaDetalle> PlanFacturaDetalles { get; set; }
    }
}
