//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Representante
    {
        public string ReprDocumento { get; set; }
        public int TDocumento { get; set; }
        public string ReprPadrNombre { get; set; }
        public string ReprApellido { get; set; }
        public string ReprParentezco { get; set; }
        public bool EstaDesabilitado { get; set; }
    }
}
