//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public int RoleSecuencia { get; set; }
        public string RoleDescripcion { get; set; }
        public Nullable<int> UsuaSecuencia { get; set; }
        public Nullable<System.DateTime> RoleFechaCreacion { get; set; }
        public Nullable<int> UsuaSecuenciaModificacion { get; set; }
        public Nullable<System.DateTime> RoleFechaModificacion { get; set; }
        public bool EstaDesabilitado { get; set; }
    }
}
