//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoCompromiso
    {
        public int TCompSecuencia { get; set; }
        public string TCompCodigo { get; set; }
        public string TCompNombre { get; set; }
        public string TCompDescripcion { get; set; }
    }
}
