//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioConsultorio
    {
        public int UsuaSecuencia_fk { get; set; }
        public int ConsSecuencia_fk { get; set; }
        public int clinSecuencia_fk { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public int UConsSecuencia { get; set; }
        public string clinRazonSocial { get; set; }
        public string ConsCodigo { get; set; }
        public string ConsDescripcion { get; set; }
        public Nullable<int> UsuaSecuenciaCreacion { get; set; }
        public Nullable<System.DateTime> UConsFechaCreacion { get; set; }
        public Nullable<int> UsuaSecuenciaModificacion { get; set; }
        public Nullable<System.DateTime> UConsFechaModificacion { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
