//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ConsultorioDoctor
    {
        public int DoctSecuencia_fk { get; set; }
        public int ClinSecuencia_fk { get; set; }
        public int ConsSecuencia { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public string ConsCodigo { get; set; }
        public string ConsDescripcion { get; set; }
        public int clinSecuencia { get; set; }
        public string clinRazonSocial { get; set; }
    }
}
