//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorMedicalWeb.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ListDeFormuriosbyRolyUser
    {
        public int UsuaSecuencia { get; set; }
        public Nullable<int> PlanSecuencia_fk { get; set; }
        public int RoleSecuencia_fk { get; set; }
        public int DoctSecuencia_fk { get; set; }
        public int RFSecuencia { get; set; }
        public int FormSecuencia_fk { get; set; }
        public string FormDescripcion { get; set; }
        public int TFormSecuencia_fk { get; set; }
        public string FormPantalla { get; set; }
    }
}
