//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alergia
    {
        public Alergia()
        {
            this.ConsultaMedicalHistorialAlergias = new HashSet<ConsultaMedicalHistorialAlergia>();
        }
    
        public int DoctSecuencia_fk { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public int ClinSecuencia_fk { get; set; }
        public int ConsSecuencia_fk { get; set; }
        public int AlerSecuencia { get; set; }
        public string AlerNombre { get; set; }
        public string AlerDescripcion { get; set; }
    
        public virtual ICollection<ConsultaMedicalHistorialAlergia> ConsultaMedicalHistorialAlergias { get; set; }
    }
}
