//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditoria
    {
        public int AudiSecuencia { get; set; }
        public Nullable<int> PaisSecuencia { get; set; }
        public Nullable<int> ClinSecuencia { get; set; }
        public Nullable<int> ConsSecuencia { get; set; }
        public Nullable<int> DoctSecuencia { get; set; }
        public Nullable<int> PersSecuencia { get; set; }
        public Nullable<int> TPersSecuencia { get; set; }
        public Nullable<System.DateTime> AudiFechaMaquina { get; set; }
        public Nullable<System.DateTime> AudiFechaServidor { get; set; }
        public string AudiValorOriginal { get; set; }
        public string AudiValorNuevo { get; set; }
        public Nullable<int> UsuaCodigo { get; set; }
        public string AudiIpMaquina { get; set; }
        public string PagiSecuencia { get; set; }
        public Nullable<int> TablSecuencia { get; set; }
        public string Accion { get; set; }
        public string DescripcionError { get; set; }
        public bool EstaDesabilitado { get; set; }
    }
}
