//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cirugia
    {
        public Cirugia()
        {
            this.ConsultaMedicaCirugias = new HashSet<ConsultaMedicaCirugia>();
        }
    
        public int DoctSecuencia_fk { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public int ClinSecuencia_fk { get; set; }
        public int ConsSecuencia_fk { get; set; }
        public int CiruSecuencia { get; set; }
        public string CiruCodigo { get; set; }
        public string CiruNombre { get; set; }
        public string CiruDescripcion { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual ICollection<ConsultaMedicaCirugia> ConsultaMedicaCirugias { get; set; }
    }
}
