//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int DoctSecuencia_fk { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public int ClinSecuencia_fk { get; set; }
        public int ConsSecuencia_fk { get; set; }
        public int PaciSecuencia_fk { get; set; }
        public Nullable<int> PersSecuencia_fk { get; set; }
        public Nullable<int> CPersSecuencia_fk { get; set; }
        public int CitaSecuencia { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Tiempo { get; set; }
        public bool CitaLlego { get; set; }
        public bool CitaAtendido { get; set; }
        public bool CitaCancelada { get; set; }
        public string CitaCancelacionMotivo { get; set; }
        public Nullable<int> FactSecuencia_fk { get; set; }
        public string CitaMotivoCita { get; set; }
        public System.DateTime CitaFechaModificacion { get; set; }
        public int UsuaSecuenciaCreacion { get; set; }
        public System.DateTime CitaFechaCreacion { get; set; }
        public int UsuaSecuenciaModificacion { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Factura Factura { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual Personal Personal { get; set; }
    }
}
