//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clinica
    {
        public Clinica()
        {
            this.Consultorios = new HashSet<Consultorio>();
        }
    
        public int clinSecuencia { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public string clinRazonSocial { get; set; }
        public string clinEstablecimiento { get; set; }
        public string clinOrganismoSuperior { get; set; }
        public string clinDireccion { get; set; }
        public string clinTelefono { get; set; }
        public string clinTelefono2 { get; set; }
        public Nullable<int> clinRNC { get; set; }
        public Nullable<int> clinFax { get; set; }
        public string clinPaginaWeb { get; set; }
        public string clinEmail { get; set; }
        public string clinFotoName { get; set; }
        public string clinFotoPath { get; set; }
        public string clinCuerpoCartaCabecera { get; set; }
        public string clinCuerpoCartaPie { get; set; }
        public Nullable<decimal> clinLatitud { get; set; }
        public Nullable<decimal> clinLongitud { get; set; }
        public Nullable<bool> clinEstaBorrado { get; set; }
        public Nullable<int> usuaSecuenciaCreacion { get; set; }
        public Nullable<int> usuaSecuenciaModificacion { get; set; }
        public Nullable<System.DateTime> clinFechaCreacion { get; set; }
        public Nullable<System.DateTime> clinFechaModificacion { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual Pai Pai { get; set; }
        public virtual ICollection<Consultorio> Consultorios { get; set; }
    }
}
