//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaMedicaHistorialEnfermeda
    {
        public int DoctSecuencia_fk { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public int ClinSecuencia_fk { get; set; }
        public int ConsSecuencia_fk { get; set; }
        public int PaciSecuencia_fk { get; set; }
        public int CMHistSecuencia_fk { get; set; }
        public int EnfeSecuencia_fk { get; set; }
        public string EnfeComentario { get; set; }
        public bool EnfermedadActiva { get; set; }
        public Nullable<System.DateTime> FechaDeDiagnostico { get; set; }
        public bool EnfermedadInfecciosa { get; set; }
        public Nullable<int> EdadMomentoDiagnosticado { get; set; }
    
        public virtual Enfermedad Enfermedad { get; set; }
    }
}
