//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultorio
    {
        public int DoctSecuencia_fk { get; set; }
        public int ConsSecuencia { get; set; }
        public int ClinSecuencia_fk { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public string ConsCodigo { get; set; }
        public string ConsDescripcion { get; set; }
        public string ConsDireccion { get; set; }
        public string ConsTelefono { get; set; }
        public string ConsExtencion { get; set; }
        public string ConsTelefono2 { get; set; }
        public string ConsExtension2 { get; set; }
        public Nullable<int> UsuaSecuenciaCreacion { get; set; }
        public Nullable<System.DateTime> ConsFechaCreacion { get; set; }
        public Nullable<int> UsuaSecuenciaModificacion { get; set; }
        public Nullable<System.DateTime> ConsFechaModificacion { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual Clinica Clinica { get; set; }
        public virtual Pai Pai { get; set; }
    }
}
