//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaMedicaHistorial
    {
        public ConsultaMedicaHistorial()
        {
            this.ConsultaMedicaHistorialEvaluacionFisicas = new HashSet<ConsultaMedicaHistorialEvaluacionFisica>();
            this.ConsultaMedicaHistorialTratamientoes = new HashSet<ConsultaMedicaHistorialTratamiento>();
            this.ConsultaMedicaHistorialDiagnosticoes = new HashSet<ConsultaMedicaHistorialDiagnostico>();
            this.ConsultaMedicaHistorialMotivoConsultas = new HashSet<ConsultaMedicaHistorialMotivoConsulta>();
        }
    
        public int DoctSecuencia_fk { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public int ClinSecuencia_fk { get; set; }
        public int ConsSecuencia_fk { get; set; }
        public int PaciSecuencia_fk { get; set; }
        public int CMHistSecuencia { get; set; }
        public string TratComentario { get; set; }
        public string MotiComentario { get; set; }
        public string EFisiComentario { get; set; }
        public string DiagComentario { get; set; }
        public Nullable<System.DateTime> CMHistFechaUltimaRegla { get; set; }
        public Nullable<decimal> CMHistIndiceMasaCorporal { get; set; }
        public string CMHistUnidadesMedidaPeso { get; set; }
        public Nullable<decimal> CMHistPeso { get; set; }
        public string CMHistUnidadesMedidaTalla { get; set; }
        public Nullable<decimal> CMHistTalla { get; set; }
        public string CMHistCodigo { get; set; }
        public Nullable<System.DateTime> CMHistFecha { get; set; }
        public Nullable<System.TimeSpan> CMHistHora { get; set; }
        public string CMHistComentario { get; set; }
        public Nullable<int> UsuaSecuenciaCreacion { get; set; }
        public System.DateTime UsuaFechaCreacion { get; set; }
        public Nullable<int> UsuaSecuenciaModificacion { get; set; }
        public Nullable<System.DateTime> UsuaFechaModificacion { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual ICollection<ConsultaMedicaHistorialEvaluacionFisica> ConsultaMedicaHistorialEvaluacionFisicas { get; set; }
        public virtual ICollection<ConsultaMedicaHistorialTratamiento> ConsultaMedicaHistorialTratamientoes { get; set; }
        public virtual ICollection<ConsultaMedicaHistorialDiagnostico> ConsultaMedicaHistorialDiagnosticoes { get; set; }
        public virtual ICollection<ConsultaMedicaHistorialMotivoConsulta> ConsultaMedicaHistorialMotivoConsultas { get; set; }
    }
}
