//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnostico
    {
        public Diagnostico()
        {
            this.ConsultaMedicaHistorialDiagnosticoes = new HashSet<ConsultaMedicaHistorialDiagnostico>();
        }
    
        public int DoctSecuencia_fk { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public int ClinSecuencia_fk { get; set; }
        public int ConsSecuencia_fk { get; set; }
        public int DiagSecuencia { get; set; }
        public string DiagCodigo { get; set; }
        public string DiagNombre { get; set; }
        public string DiagDescripcion { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual ICollection<ConsultaMedicaHistorialDiagnostico> ConsultaMedicaHistorialDiagnosticoes { get; set; }
    }
}
