//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public Doctor()
        {
            this.ArchivosPacientes = new HashSet<ArchivosPaciente>();
            this.Citas = new HashSet<Cita>();
            this.ConsultaMedicas = new HashSet<ConsultaMedica>();
            this.ConsultaMedicaHistorials = new HashSet<ConsultaMedicaHistorial>();
            this.ImagenDoctors = new HashSet<ImagenDoctor>();
            this.InstitucionesAseguradoras = new HashSet<InstitucionesAseguradora>();
            this.Pacientes = new HashSet<Paciente>();
            this.Procedimientos = new HashSet<Procedimiento>();
            this.Recetas = new HashSet<Receta>();
            this.TipoArchivoPacientes = new HashSet<TipoArchivoPaciente>();
        }
    
        public int DoctSecuencia { get; set; }
        public int UsuSecuencia { get; set; }
        public string DoctCUPRE { get; set; }
        public string DoctDocumento { get; set; }
        public Nullable<int> TDSecuencia { get; set; }
        public string DoctNombre { get; set; }
        public string DoctApellido { get; set; }
        public Nullable<System.DateTime> DoctFechaNacimiento { get; set; }
        public int EspeSecuencia { get; set; }
        public string DoctDireccion { get; set; }
        public string DoctTelefono { get; set; }
        public string DoctCelular { get; set; }
        public Nullable<int> UsuaSecuenciaCreacion { get; set; }
        public Nullable<System.DateTime> DoctFechaCreacion { get; set; }
        public Nullable<int> UsuaSecuenciaModificacion { get; set; }
        public Nullable<System.DateTime> DoctFechaModificacion { get; set; }
        public string DoctGenero { get; set; }
        public int PaisSecuencia { get; set; }
        public string DoctFotoPath { get; set; }
        public string DoctFotoNombre { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual ICollection<ArchivosPaciente> ArchivosPacientes { get; set; }
        public virtual ICollection<Cita> Citas { get; set; }
        public virtual ICollection<ConsultaMedica> ConsultaMedicas { get; set; }
        public virtual ICollection<ConsultaMedicaHistorial> ConsultaMedicaHistorials { get; set; }
        public virtual Especialidade Especialidade { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<ImagenDoctor> ImagenDoctors { get; set; }
        public virtual ICollection<InstitucionesAseguradora> InstitucionesAseguradoras { get; set; }
        public virtual ICollection<Paciente> Pacientes { get; set; }
        public virtual ICollection<Procedimiento> Procedimientos { get; set; }
        public virtual ICollection<Receta> Recetas { get; set; }
        public virtual ICollection<TipoArchivoPaciente> TipoArchivoPacientes { get; set; }
    }
}
