//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enfermedad
    {
        public Enfermedad()
        {
            this.ConsultaMedicaEnfermedas = new HashSet<ConsultaMedicaEnfermeda>();
            this.ConsultaMedicaHistorialEnfermedas = new HashSet<ConsultaMedicaHistorialEnfermeda>();
        }
    
        public int DoctSecuencia_fk { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public int ClinSecuencia_fk { get; set; }
        public int ConsSecuencia_fk { get; set; }
        public int EnfeSecuencia { get; set; }
        public string EnfeNombre { get; set; }
        public string EnfeDescripcion { get; set; }
    
        public virtual ICollection<ConsultaMedicaEnfermeda> ConsultaMedicaEnfermedas { get; set; }
        public virtual ICollection<ConsultaMedicaHistorialEnfermeda> ConsultaMedicaHistorialEnfermedas { get; set; }
    }
}
