//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Especialidade
    {
        public Especialidade()
        {
            this.Doctors = new HashSet<Doctor>();
            this.EspecialidadFormularioCampos = new HashSet<EspecialidadFormularioCampos>();
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public int EspeSecuencia { get; set; }
        public string EspeNombre { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual ICollection<Doctor> Doctors { get; set; }
        public virtual ICollection<EspecialidadFormularioCampos> EspecialidadFormularioCampos { get; set; }
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
