//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluacionFisica
    {
        public EvaluacionFisica()
        {
            this.ConsultaMedicaHistorialEvaluacionFisicas = new HashSet<ConsultaMedicaHistorialEvaluacionFisica>();
        }
    
        public int DoctSecuencia_fk { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public int ClinSecuencia_fk { get; set; }
        public int ConsSecuencia_fk { get; set; }
        public int EFisiSecuencia { get; set; }
        public string EFisiCodigoNombre { get; set; }
        public string EFisiDescripcion { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual ICollection<ConsultaMedicaHistorialEvaluacionFisica> ConsultaMedicaHistorialEvaluacionFisicas { get; set; }
    }
}
