//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaEstado
    {
        public FacturaEstado()
        {
            this.Facturas = new HashSet<Factura>();
        }
    
        public int DoctSecuencia_fk { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public int ClinSecuencia_fk { get; set; }
        public int ConsSecuencia_fk { get; set; }
        public int FEstaSecuencia { get; set; }
        public string FEstaNombre { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual ICollection<Factura> Facturas { get; set; }
    }
}
