//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formulario
    {
        public Formulario()
        {
            this.EspecialidadFormularioCampos = new HashSet<EspecialidadFormularioCampos>();
            this.RolFormularios = new HashSet<RolFormulario>();
        }
    
        public int FormSecuencia { get; set; }
        public string FormDescripcion { get; set; }
        public int TFormSecuencia_fk { get; set; }
        public string FormPantalla { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual ICollection<EspecialidadFormularioCampos> EspecialidadFormularioCampos { get; set; }
        public virtual TipoFormulario TipoFormulario { get; set; }
        public virtual ICollection<RolFormulario> RolFormularios { get; set; }
    }
}
