//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormularioCampos
    {
        public FormularioCampos()
        {
            this.EspecialidadFormularioCampos = new HashSet<EspecialidadFormularioCampos>();
        }
    
        public int FCampSecuencia { get; set; }
        public string FCampIdNombre { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual ICollection<EspecialidadFormularioCampos> EspecialidadFormularioCampos { get; set; }
    }
}
