//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstitucionesAseguradora
    {
        public InstitucionesAseguradora()
        {
            this.InstitucionAseguradoraPlanes = new HashSet<InstitucionAseguradoraPlane>();
            this.Pacientes = new HashSet<Paciente>();
        }
    
        public int DoctSecuencia { get; set; }
        public int ClinSecuencia { get; set; }
        public int ConsSecuencia { get; set; }
        public int IAsegSecuencia { get; set; }
        public Nullable<int> IAsegCodigo { get; set; }
        public string IAsegNombre { get; set; }
        public int IAsegRNC { get; set; }
        public string IAsegTelefono { get; set; }
        public string IAsegCorreo { get; set; }
        public string IAsegWeb { get; set; }
        public Nullable<int> usuaSecuenciaCreacion { get; set; }
        public Nullable<int> usuaSecuenciaModificacion { get; set; }
        public Nullable<System.DateTime> IAsegFechaCreacion { get; set; }
        public Nullable<System.DateTime> IAsegFechaModificacion { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual ICollection<InstitucionAseguradoraPlane> InstitucionAseguradoraPlanes { get; set; }
        public virtual ICollection<Paciente> Pacientes { get; set; }
    }
}
