//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicamento
    {
        public Medicamento()
        {
            this.RecetaMedicamentos = new HashSet<RecetaMedicamento>();
        }
    
        public int DoctSecuencia_fk { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public int ClinSecuencia_fk { get; set; }
        public int ConsSecuencia_fk { get; set; }
        public int MediSecuencia { get; set; }
        public string MediCodigo { get; set; }
        public string MediNombre { get; set; }
        public string MediLaboratorio { get; set; }
        public string MediFamilia { get; set; }
        public string MediDescripcion { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual ICollection<RecetaMedicamento> RecetaMedicamentos { get; set; }
    }
}
