//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moneda
    {
        public Moneda()
        {
            this.Planes = new HashSet<Plane>();
            this.Procedimientos = new HashSet<Procedimiento>();
        }
    
        public int MoneSecuencia { get; set; }
        public string MoneMoneda { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual ICollection<Plane> Planes { get; set; }
        public virtual ICollection<Procedimiento> Procedimientos { get; set; }
    }
}
