//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotivoConsulta
    {
        public MotivoConsulta()
        {
            this.ConsultaMedicaHistorialMotivoConsultas = new HashSet<ConsultaMedicaHistorialMotivoConsulta>();
        }
    
        public int DoctSecuencia_fk { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public int ClinSecuencia_fk { get; set; }
        public int ConsSecuencia_fk { get; set; }
        public int MConsSecuencia { get; set; }
        public string MConsMotivoConsulta { get; set; }
        public string MConsDescripcion { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual ICollection<ConsultaMedicaHistorialMotivoConsulta> ConsultaMedicaHistorialMotivoConsultas { get; set; }
    }
}
