//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pai
    {
        public Pai()
        {
            this.Clinicas = new HashSet<Clinica>();
            this.Consultorios = new HashSet<Consultorio>();
            this.HorariosDiaTrabajoes = new HashSet<HorariosDiaTrabajo>();
            this.Pacientes = new HashSet<Paciente>();
            this.Personals = new HashSet<Personal>();
        }
    
        public int PaisSecuencia { get; set; }
        public string PaisNombre { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual ICollection<Clinica> Clinicas { get; set; }
        public virtual ICollection<Consultorio> Consultorios { get; set; }
        public virtual ICollection<HorariosDiaTrabajo> HorariosDiaTrabajoes { get; set; }
        public virtual ICollection<Paciente> Pacientes { get; set; }
        public virtual ICollection<Personal> Personals { get; set; }
    }
}
