//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIATRIAeMBARAZO
    {
        public Nullable<int> GESTACIONNumero { get; set; }
        public string obstetra { get; set; }
        public Nullable<int> duracionSemanas { get; set; }
        public Nullable<bool> diabetes { get; set; }
        public Nullable<bool> hipertension { get; set; }
        public Nullable<bool> tramatismo { get; set; }
        public string infrecciones { get; set; }
        public string asma { get; set; }
        public string mediacion { get; set; }
        public string observacion { get; set; }
        public bool EstaDesabilitado { get; set; }
    }
}
