//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        public Personal()
        {
            this.Citas = new HashSet<Cita>();
            this.Facturas = new HashSet<Factura>();
        }
    
        public int DoctSecuencia_fk { get; set; }
        public int PersSecuencia { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public string PersDocumento { get; set; }
        public int TDSecuencia_fk { get; set; }
        public Nullable<int> UsuaSecuencia { get; set; }
        public string PersNombre { get; set; }
        public string PersApellido { get; set; }
        public Nullable<System.DateTime> PersFechaNacimiento { get; set; }
        public string PersDireccion { get; set; }
        public int CPersSecuencia_FK { get; set; }
        public string PersTelefono { get; set; }
        public string PersCelular { get; set; }
        public bool EstaActivo { get; set; }
        public string PersGenero { get; set; }
        public Nullable<int> UsuaCreacion { get; set; }
        public Nullable<System.DateTime> PersFechaCreacion { get; set; }
        public Nullable<int> UsuaModificacion { get; set; }
        public Nullable<System.DateTime> PersFechaModificacion { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual ICollection<Cita> Citas { get; set; }
        public virtual ICollection<Factura> Facturas { get; set; }
        public virtual Pai Pai { get; set; }
    }
}
