//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plane
    {
        public Plane()
        {
            this.PlanFacturaDetalles = new HashSet<PlanFacturaDetalle>();
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public int PlanSecuencia { get; set; }
        public string PlanDescripcion { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public int MoneSecuencia_fk { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual Moneda Moneda { get; set; }
        public virtual ICollection<PlanFacturaDetalle> PlanFacturaDetalles { get; set; }
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
