//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receta
    {
        public Receta()
        {
            this.RecetaAnalisisClinicoes = new HashSet<RecetaAnalisisClinico>();
            this.RecetaImagenes = new HashSet<RecetaImagene>();
            this.RecetaMedicamentos = new HashSet<RecetaMedicamento>();
            this.RecetaPacienteVacunas = new HashSet<RecetaPacienteVacuna>();
        }
    
        public int DoctSecuencia_fk { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public int ClinSecuencia_fk { get; set; }
        public int ConsSecuencia_fk { get; set; }
        public int PaciSecuencia_fk { get; set; }
        public int ReceSecuencia { get; set; }
        public int CMHistSecuencia_fk { get; set; }
        public System.DateTime ReceFecha { get; set; }
        public string ReceInstruccionesFarmacia { get; set; }
        public string ReceInstruccionesAlPaciente { get; set; }
        public string ReceComentario { get; set; }
        public Nullable<int> UsuaSecuenciaCreacion { get; set; }
        public Nullable<System.DateTime> UsuaFechaCreacion { get; set; }
        public Nullable<int> UsuaSecuenciaModificacion { get; set; }
        public Nullable<System.DateTime> UsuaFechaModificacion { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual ICollection<RecetaAnalisisClinico> RecetaAnalisisClinicoes { get; set; }
        public virtual ICollection<RecetaImagene> RecetaImagenes { get; set; }
        public virtual ICollection<RecetaMedicamento> RecetaMedicamentos { get; set; }
        public virtual ICollection<RecetaPacienteVacuna> RecetaPacienteVacunas { get; set; }
    }
}
