//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Representante
    {
        public string ReprDocumento { get; set; }
        public int TDocumento { get; set; }
        public string ReprPadrNombre { get; set; }
        public string ReprApellido { get; set; }
        public string ReprParentezco { get; set; }
        public bool EstaDesabilitado { get; set; }
    }
}
