//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public int RoleSecuencia { get; set; }
        public string RoleDescripcion { get; set; }
        public Nullable<int> UsuaSecuencia { get; set; }
        public Nullable<System.DateTime> RoleFechaCreacion { get; set; }
        public Nullable<int> UsuaSecuenciaModificacion { get; set; }
        public Nullable<System.DateTime> RoleFechaModificacion { get; set; }
        public bool EstaDesabilitado { get; set; }
    }
}
