//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolFormulario
    {
        public int DoctSecuencia_fk { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public int ClinSecuencia_fk { get; set; }
        public int ConsSecuencia_fk { get; set; }
        public int RFSecuencia { get; set; }
        public int RoleSecuencia_fk { get; set; }
        public int FormSecuencia_fk { get; set; }
        public Nullable<int> PlanSecuencia_fk { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual Formulario Formulario { get; set; }
    }
}
