//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoArchivoPaciente
    {
        public TipoArchivoPaciente()
        {
            this.ArchivosPacientes = new HashSet<ArchivosPaciente>();
        }
    
        public int DoctSecuencia_fk { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public int ClinSecuencia_fk { get; set; }
        public int ConsSecuencia_fk { get; set; }
        public int TAPaciSecuencia { get; set; }
        public string TAPaciNombre { get; set; }
    
        public virtual ICollection<ArchivosPaciente> ArchivosPacientes { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
