//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDocumento
    {
        public TipoDocumento()
        {
            this.Pacientes = new HashSet<Paciente>();
        }
    
        public int TDSecuencia { get; set; }
        public string TDDocumento { get; set; }
    
        public virtual ICollection<Paciente> Pacientes { get; set; }
    }
}
