//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tratamiento
    {
        public Tratamiento()
        {
            this.ConsultaMedicaHistorialTratamientoes = new HashSet<ConsultaMedicaHistorialTratamiento>();
        }
    
        public int DoctSecuencia_fk { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public int ClinSecuencia_fk { get; set; }
        public int ConsSecuencia_fk { get; set; }
        public int TratSecuencia { get; set; }
        public string TratCodigo { get; set; }
        public string TratNombre { get; set; }
        public string TratDescripcion { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual ICollection<ConsultaMedicaHistorialTratamiento> ConsultaMedicaHistorialTratamientoes { get; set; }
    }
}
