//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Doctors = new HashSet<Doctor>();
            this.PlanFacturas = new HashSet<PlanFactura>();
            this.UsuarioConsultorios = new HashSet<UsuarioConsultorio>();
        }
    
        public int UsuaSecuencia { get; set; }
        public string UsuaEmail { get; set; }
        public string UsuaClave { get; set; }
        public string UsuaNombre { get; set; }
        public string UsuaApellido { get; set; }
        public Nullable<System.DateTime> UsuaFechaNacimiento { get; set; }
        public string UsuaGenero { get; set; }
        public Nullable<int> RoleSecuencia_fk { get; set; }
        public int UsuaIntentos { get; set; }
        public int PaisSecuencia { get; set; }
        public Nullable<int> PlanSecuencia_fk { get; set; }
        public Nullable<int> EspeSecuencia_fk { get; set; }
        public Nullable<int> UsuaSecuenciaCreacion { get; set; }
        public Nullable<System.DateTime> UsuaFechaCreacion { get; set; }
        public Nullable<int> UsuaSecuenciaModificacion { get; set; }
        public Nullable<System.DateTime> UsuaFechaModificacion { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual ICollection<Doctor> Doctors { get; set; }
        public virtual Especialidade Especialidade { get; set; }
        public virtual Plane Plane { get; set; }
        public virtual ICollection<PlanFactura> PlanFacturas { get; set; }
        public virtual ICollection<UsuarioConsultorio> UsuarioConsultorios { get; set; }
    }
}
