//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioConsultorio
    {
        public int UsuaSecuencia_fk { get; set; }
        public int ConsSecuencia_fk { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public int clinSecuencia_fk { get; set; }
        public int UConsSecuencia { get; set; }
        public string clinRazonSocial { get; set; }
        public string ConsCodigo { get; set; }
        public string ConsDescripcion { get; set; }
        public Nullable<int> UsuaSecuenciaCreacion { get; set; }
        public Nullable<System.DateTime> UConsFechaCreacion { get; set; }
        public Nullable<int> UsuaSecuenciaModificacion { get; set; }
        public Nullable<System.DateTime> UConsFechaModificacion { get; set; }
        public bool EstaDesabilitado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
