//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacuna
    {
        public Vacuna()
        {
            this.RecetaPacienteVacunas = new HashSet<RecetaPacienteVacuna>();
        }
    
        public int DoctSecuencia_fk { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public int ClinSecuencia_fk { get; set; }
        public int ConsSecuencia_fk { get; set; }
        public int VacuSecuencia { get; set; }
        public string VacuNombre { get; set; }
        public Nullable<int> AEdadAnio { get; set; }
        public Nullable<int> AEdadMeses { get; set; }
        public Nullable<int> AEdadDias { get; set; }
    
        public virtual ICollection<RecetaPacienteVacuna> RecetaPacienteVacunas { get; set; }
    }
}
