//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ConsultorioDoctor
    {
        public int DoctSecuencia_fk { get; set; }
        public int ClinSecuencia_fk { get; set; }
        public int ConsSecuencia { get; set; }
        public int PaisSecuencia_fk { get; set; }
        public string ConsCodigo { get; set; }
        public string ConsDescripcion { get; set; }
        public int clinSecuencia { get; set; }
        public string clinRazonSocial { get; set; }
    }
}
