//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsignacionformularioPlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ListDeFormuriosbyRolyUser
    {
        public int UsuaSecuencia { get; set; }
        public Nullable<int> PlanSecuencia_fk { get; set; }
        public int RoleSecuencia_fk { get; set; }
        public int DoctSecuencia_fk { get; set; }
        public int RFSecuencia { get; set; }
        public int FormSecuencia_fk { get; set; }
        public string FormDescripcion { get; set; }
        public int TFormSecuencia_fk { get; set; }
        public string FormPantalla { get; set; }
    }
}
